package DBMain.ParseExceptions;

public enum DomainType {DATABASENAME, TABLENAME, ATTRIBUTENAME, FIRSTCOMMAND,
	VALUES, VALUE, INTO, FROM, SET, WHERE, TABLE,
	OPERATOR, BRACKET, SEMICOLON, COMMA, UNKNOWN}
