package DBMain.ParseExceptions;

public enum DomainType {DATABASENAME, TABLENAME, ATTRIBUTENAME, FIRSTCOMMAND,
	VALUES, VALUE, INTO, FROM, SET, WHERE, TABLE, AND, ON,
	OPERATOR, BRACKET, SEMICOLON, COMMA, UNKNOWN}
